services:
  mongo-hotels:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo-hotels:27017/
    depends_on:
      - mongo-hotels

  # storage:
  #   image: redis
  #   volumes:
  #     - ./data:/data
  
  backend:
    image: node:20.11
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - PORT=4000
      - MONGO_CONNECTION=mongodb://mongo-hotels:27017/hotels
      - JWT_SECRET=secret_s3ui4er76n7s8ieu9rn90hfauiSerGFnGfawfjGjhGfaGkjshda
    ports:
      - 4000:4000
    command: npm run start:dev
    depends_on:
      - mongo-hotels

  frontend:
    image: node:20.11
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - PORT=3000
      - REACT_APP_BACK_URL=http://localhost:4000
      - REACT_APP_POSTFIX_LOGIN=/api/auth/login
      - REACT_APP_POSTFIX_SIGNUP=/api/auth/signup
      - REACT_APP_POSTFIX_USERS=/api/admin/users
      - REACT_APP_POSTFIX_HOTELS=/api/admin/hotels
      - REACT_APP_POSTFIX_ROOMS=/api/admin/hotel-rooms
      - REACT_APP_POSTFIX_RESERVATION=/api/client/reservations
    ports:
      - 3000:3000
    command: npm run start
    depends_on:
      - mongo-hotels
      - backend
